# Site settings
title: cartopixels.com
description: Geospatial Consultant and Data Solution
baseurl: "" # the subpath of your site, e.g. /blog/
url: cartopixels.com # the base hostname & protocol for your site
port: 4002

email: mail@cartopixels.com

encoding: utf-8
# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-autoprefixer
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - github-page

# exclude
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock