# Site settings
title: cartopixels
email: wslerry2@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: cartopixels.com # the base hostname & protocol for your site
port: 4002
twitter_username: Lerry_WS
github_username: wslerry

# Build settings
markdown: kramdown
