# Site settings
title: cartopixels.com
email: cartopixels@outlook.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: cartopixels.com # the base hostname & protocol for your site
port: 4002
twitter_username: wslerry
github_username: wslerry
encoding: utf-8
# Build settings
markdown: kramdown
