# Site settings
title: cartopixels.com
description: >- 
  Geospatial Consultation and Data Solution
tagline: Geospatial Consultation and Data Solution
baseurl: "" # the subpath of your site, e.g. /blog/
url: cartopixels.com # the base hostname & protocol for your site
lang: en_US
port: 4002
maintenance: false
email: mail@cartopixels.com
image: /favicon/cartopixels_200x200.png
encoding: utf-8

# Build settings
markdown: kramdown

kramdown:
  html_to_native: true
  
# sass:
  # indentWidth: 4
  # style: compressed
  # precision: 10

plugins:
  - jekyll-sitemap
  - jekyll-autoprefixer
  # - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - github-page

# permalinks
# permalink: /posts/:title

# webrick:
#   headers:
#       X-Frame-Options : DENY
#       X-XSS-Protection: 1; mode=block
#       Content-Security-Policy: default-src 'unsafe-inline' 'none' https://github.com https://raw.githubusercontent.com;
#               font-src 'self' https://fonts.googleapis.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net;
#               img-src 'self' *;
#               object-src 'none';
#               script-src 'unsafe-inline' 'self' http://code.jquery.com https://cdn.jsdelivr.net http://cdnjs.cloudflare.com https://badge.fury.io;
#               style-src 'unsafe-inline' 'self' https://cdnjs.cloudflare.com http://cdn.jsdelivr.net https://cdn.knightlab.com;
#       Referrer-Policy: no-referrer, strict-origin-when-cross-origin
#       Strict-Transport-Security: max-age=63072000

# exclude
exclude:
  - .gitignore
  - Gemfile.lock